apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: tz5ggd1i9-dotnet-basic
  janus-idp.io/tekton: tz5ggd1i9-dotnet-basic
  backstage.io/kubernetes-id: tz5ggd1i9-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tz5ggd1i9-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
